workflows:
  flutter-android:
    name: VNNO by JPR - Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.vnno.jpr"
    scripts:
      - name: Obtener dependencias
        script: |
          flutter pub get
      - name: Compilar APK release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - pisanojr83@gmail.com
