workflows:
  flutter-android:
    name: VNNO by JPR - Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.vnno.jpr"
    scripts:
      - name: Regenerar módulo Android limpio (embedding v2)
        script: |
          rm -rf android
          flutter create --platforms=android --org com.vnno.jpr .
      - name: Ajustes Gradle (desugaring + Kotlin + repos)
        script: |
          # android/app/build.gradle
          cat > android/app/build.gradle <<'EOF'
          plugins {
              id "com.android.application"
              id "kotlin-android"
              id "dev.flutter.flutter-gradle-plugin"
          }

          android {
              namespace "com.vnno.jpr"
              compileSdkVersion 34

              defaultConfig {
                  applicationId "com.vnno.jpr"
                  minSdkVersion 21
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
                  multiDexEnabled true
              }

              compileOptions {
                  coreLibraryDesugaringEnabled true
                  sourceCompatibility JavaVersion.VERSION_1_8
                  targetCompatibility JavaVersion.VERSION_1_8
              }

              kotlinOptions { jvmTarget = "1.8" }

              buildTypes {
                  release {
                      minifyEnabled false
                      shrinkResources false
                      signingConfig signingConfigs.debug
                  }
              }
          }

          flutter { source "../.." }

          dependencies {
              implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0"
              coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.0.4"
          }
          EOF

          # android/build.gradle
          cat > android/build.gradle <<'EOF'
          buildscript {
              ext.kotlin_version = '1.9.0'
              repositories { google(); mavenCentral() }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.2.2'
                  classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
              }
          }
          allprojects { repositories { google(); mavenCentral() } }
          rootProject.buildDir = "../build"
          subprojects { project.buildDir = "${rootProject.buildDir}/${project.name}" }
          subprojects { project.evaluationDependsOn(":app") }
          tasks.register("clean", Delete) { delete rootProject.buildDir }
          EOF
            - name: flutter pub get
        script: flutter pub get

      - name: Compilar APKs por ABI 
        script: |
          flutter build apk --release --split-per-abi

      - name: Compilar APK debug para emulador
        script: |
          flutter build apk --debug --target-platform=android-x64

    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - pisanojr83@gmail.com


