name: vnno_by_jpr
description: VNNO by JPR - app financiera (plantilla inicial)
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.0
  flutter_local_notifications: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
